html/protected/controllers/MemberController.php
<?php

class MemberController extends AccessController {

    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/column1';
    public $module = 'member';
    public $filename = 'Report_Member';

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id) {
        $this->render('view', array(
            'model' => $this->loadModel($id),
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionImport() {
        $model = new Member;
	$rs = array();
        if (isset($_POST['Member'])) {
            $model->service_id = $_POST['Member']['service_id'];
            $model->fileMember = CUploadedFile::getInstance($model, 'list_member');
            //if ($model->validate()) {
            if (isset($model->fileMember) && $model->fileMember) {
                if ($model->fileMember->saveAs('data/import/' . $model->fileMember->getName())) {
                    $sql = '';
                    $sql_before = 'INSERT INTO member (msisdn,register_date,service_id,status,end_charging_date) VALUES ';
                    $ListMember = file('/var/www/html/data/import/' . $model->fileMember->getName());
                    if (file_get_contents('/var/www/html/data/import/' . $model->fileMember->getName())) {
                        $reg = '/^(20)[0-9]{7,8}$/';
                        $reg1 = '/^\d{4}\-[0-9]{2}-[0-9]{2}\s[0-9]{2}\:[0-9]{2}:[0-9]{2}$/';

                        foreach ($ListMember as $i) {
                            $nv = explode(',', $i);
                            if (count($nv) > 1) {
                                if (preg_match($reg, $nv[0]))
                                    $msisdn = $nv[0];
                                if (preg_match($reg1, trim($nv[1])))
                                    $Time_Reg = trim($nv[1]);
                                else
                                    $Time_Reg = date('Y-m-d H:i:s', time());
                            } else {
                                if (preg_match($reg, $i))
                                    $msisdn = $i;
                                $Time_Reg = date('Y-m-d H:i:s', time());
                            }
                            if (isset($msisdn) && isset($Time_Reg) && $msisdn && $Time_Reg)
                                if (!Member::model()->findByAttributes(array('msisdn' => '856' . $msisdn, 'status' => 1, 'service_id' => $model->service_id))){
                                    if(!in_array($msisdn, $rs)){
                                        $rsValue[] = '("856' . $msisdn . '","' . $Time_Reg . '",' . $model->service_id . ',1,now())';
                                        $rs[] = $msisdn;
                                    }
                                }
                        }
                        if (isset($rsValue) && count($rsValue) > 0) {
                            $cmd = Yii::app()->db->createCommand($sql_before . implode(',', $rsValue));
                            $cmd->execute();
                        }
                    }
                }
                $this->redirect(array('member/admin'));            }
            //}
        }
        $this->render('import', array(
            'model' => $model,
        ));
    }

    public function actionCreate() {
        $model = new Member;

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['Member'])) {
            $model->register_date = $_SERVER['REQUEST_TIME'];
            $model->attributes = $_POST['Member'];
            $model->register_date = date('Y-m-d H:i:s', time());
            $model->register_type = 1;
            $model->status = 1;
            $model->charging_status = 0;
           
            $model->msisdn = '856' . $_POST['Member']['msisdn'] . '';
            if ($model->save())
                $this->redirect(array('view', 'id' => $model->id));
        }
        $this->render('create', array(
            'model' => $model,
        ));
    }
    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id) {
        $model = $this->loadModel($id);
        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['Member'])) {
            $model->attributes = $_POST['Member'];
            if (isset($_POST['Member']['charging_status'])) {
                $model->charging_status = $_POST['Member']['charging_status'];
            }

            if ($model->status == 3 || $model->status == 4 || $model->status == 5)
                $model->cancel_date = date('Y-m-d H:i:s', time());
            if ($model->save())
                $this->redirect(array('view', 'id' => $model->id));
        }

        $this->render('update', array(
            'model' => $model,
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id) {
        $this->loadModel($id)->delete();

        // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
        if (!isset($_GET['ajax']))
            $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
    }

    /**
     * Lists all models.
     */
    public function actionIndex() {
        $dataProvider = new CActiveDataProvider('Member');
        $this->render('index', array(
            'dataProvider' => $dataProvider,
        ));
    }

    /**
     * Manages all models.
     */
    public function actionAdmin() {
        $model = new Member('search');
        $model->unsetAttributes();  // clear any default values
        if (isset($_GET['Member']))
            $model->attributes = $_GET['Member'];

        //if (Yii::app()->request->getParam('export')) {
	    //$this->exportData($model, array('msisdn', 'serviceName', 'register_date', 'cancel_date', 'status', 'sub_type'), $this->filename);
        //   Yii::app()->end();
        //}
		if(Yii::app()->request->getParam('export')) {
            $model->search();
			echo $model->export_id;
            while(1){
               $sql = "select status from command_query where id = $model->export_id ";
                $cmd = Yii::app()->db->createCommand($sql)->queryScalar();
                $file = "export/Report_Member"."_".$model->export_id."."."csv";
                if($cmd == 2){
                    $this->redirect($file);
                }else{
                    sleep(5);
                }
                //if($i++>3) break;
            }
            exit();

        }
        $this->render('admin', array(
            'model' => $model,
        ));
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer the ID of the model to be loaded
     */
    public function loadModel($id) {
        $model = Member::model()->findByPk($id);
        if ($model === null)
            throw new CHttpException(404, 'The requested page does not exist.');
        return $model;
    }

    /**
     * Performs the AJAX validation.
     * @param CModel the model to be validated
     */
    protected function performAjaxValidation($model) {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'member-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }

}

html/protected/views/member/_form.php
<?php
/* @var $this MemberController */
/* @var $model Member */
/* @var $form CActiveForm */
?>

<div class="form">

    <?php
    $form = $this->beginWidget('CActiveForm', array(
        'id' => 'member-form',
        'enableAjaxValidation' => false,
    ));
    ?>

    <p class="note">Fields with <span class="required">*</span> are required.</p>

    <?php echo $form->errorSummary($model); ?>
    <p class="note">Phone number is <span class="required">85620xxxxxxxx</span> </p>
    <div class="row">
        <?php echo $form->labelEx($model, 'msisdn'); ?>
        <?php echo $form->textField($model, 'msisdn', array('size' => 20, 'maxlength' => 50)); ?>
        <?php echo $form->error($model, 'msisdn'); ?>
    </div>

    <div class="row">
        <?php echo $form->labelEx($model, 'service_id'); ?>
        <?php echo $form->dropDownList($model, 'service_id', $model->getListService()); ?>
        <?php echo $form->error($model, 'service_id'); ?>
    </div>

    <?php if (!$model->isNewRecord): ?>
        <div class="row">
            <?php echo $form->labelEx($model, 'status'); ?>
            <?php echo $form->dropDownList($model, 'status', $model->getMemberStatus()); ?>
            <?php echo $form->error($model, 'status'); ?>
        </div>
    <?php endif; ?>

    <div class="row">
        <label>Charging money</label>
        <?php if ($this->isAdmin()) { ?>
            <?php echo $form->dropDownList($model, 'charging_status', array('' => 'Select...', 0 => 'Charge', 1 => 'Not Charge')); ?>
        <?php } else { ?>
            <span style="line-height: 26px;"><?php echo $model->charging_status == 0 ? "Charge" : "Not Charge"; ?></span>
        <?php } ?>
        <?php echo $form->error($model, 'charging_status'); ?>
    </div>

    <div class="row buttons">
        <?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
    </div>

    <?php $this->endWidget(); ?>

</div><!-- form -->

html/protected/views/member/_search.php
<?php
/* @var $this MemberController */
/* @var $model Member */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php 
    Yii::import('application.extensions.CJuiDateTimePicker.CJuiDateTimePicker');
    $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
        'enableAjaxValidation' => FALSE,
	'method'=>'get',
)); ?>

	<div class="row" style="width:25%;float:left">
		<?php echo $form->label($model,'Phone Number',array('style'=>'width:110px;')); ?>
		<?php echo $form->textField($model,'msisdn',array('size'=>20,'maxlength'=>50)); ?>
	</div>
        
        
    
        <div class="row" style="width:25%;float:left">
		<?php echo $form->label($model,'category_id',array('style'=>'width:105px;')); ?>
		<?php echo $form->dropDownlist($model,'category_id',  Service::model()->getListCategory()); ?>
	</div>

	<div class="row" style="width:25%;float:left;">
		<?php echo $form->label($model,'service_id',array('style'=>'width:110px;')); ?>
		<?php echo $form->dropDownList($model,'service_id',$model->getListService(),array('style'=>'width:140px;')); ?>
	</div>
    
        <div class="row" style="width:25%;float:left;">
		<?php echo $form->label($model,'status',array('style'=>'width:105px;')); ?>
		<?php echo $form->dropDownList($model,'status',array('' => 'Select',1=>'Active',2=>'Suspend',3=>'Cancel',4=>'Cancel By System',5=>'Cancel by admin')); ?>
	</div>
    
        <div class="row" style="width:25%;float:left">
		<?php echo $form->label($model,'register_start',array('style'=>'width:110px;')); ?>
		<?php 
                    $this->widget('CJuiDateTimePicker',array(
                    'model'=>$model, //Model object
                    'attribute'=>'register_start', //attribute name
                    'mode'=>'datetime', //use "time","date" or "datetime" (default)
                    'options'=>array("dateFormat"=>'yy/mm/dd'), // jquery plugin options
                    'language' => ''
            )); ?>
	</div>
    
        <div class="row" style="width:25%;float:left;">
		<?php echo $form->label($model,'register_end',array('style'=>'width:105px;')); ?>
		<?php 
                    $this->widget('CJuiDateTimePicker',array(
                    'model'=>$model, //Model object
                    'attribute'=>'register_end', //attribute name
                    'mode'=>'datetime', //use "time","date" or "datetime" (default)
                    'options'=>array("dateFormat"=>'yy/mm/dd'), // jquery plugin options
                    'language' => ''
            )); ?>
	</div>
    
        <div class="row" style="width:25%;float:left">
		<?php echo $form->label($model,'cancel_start',array('style'=>'width:110px;')); ?>
		<?php 
                    $this->widget('CJuiDateTimePicker',array(
                    'model'=>$model, //Model object
                    'attribute'=>'cancel_start', //attribute name
                    'mode'=>'datetime', //use "time","date" or "datetime" (default)
                    'options'=>array("dateFormat"=>'yy/mm/dd'), // jquery plugin options
                    'language' => ''
            )); ?>
	</div>
    
        <div class="row" style="width:25%;float:left;">
		<?php echo $form->label($model,'cancel_end',array('style'=>'width:105px;')); ?>
		<?php 
                    $this->widget('CJuiDateTimePicker',array(
                    'model'=>$model, //Model object
                    'attribute'=>'cancel_end', //attribute name
                    'mode'=>'datetime', //use "time","date" or "datetime" (default)
                    'options'=>array("dateFormat"=>'yy/mm/dd'), // jquery plugin options
                    'language' => ''
            )); ?>
	</div>
    
        <div class="row" style="width:25%;float:left">
		<?php echo $form->label($model,'charging_start',array('style'=>'width:110px;')); ?>
		<?php 
                    $this->widget('CJuiDateTimePicker',array(
                    'model'=>$model, //Model object
                    'attribute'=>'charging_start', //attribute name
                    'mode'=>'datetime', //use "time","date" or "datetime" (default)
                    'options'=>array("dateFormat"=>'yy/mm/dd'), // jquery plugin options
                    'language' => ''
            )); ?>
	</div>
    
        <div class="row" style="width:25%;float:left;">
		<?php echo $form->label($model,'charging_end',array('style'=>'width:105px;')); ?>
		<?php 
                    $this->widget('CJuiDateTimePicker',array(
                    'model'=>$model, //Model object
                    'attribute'=>'charging_end', //attribute name
                    'mode'=>'datetime', //use "time","date" or "datetime" (default)
                    'options'=>array("dateFormat"=>'yy/mm/dd'), // jquery plugin options
                    'language' => ''
            )); ?>
	</div>
    
        <div class="row" style="width:25%;float:left">
		<?php echo $form->label($model,'endcharge_start',array('style'=>'width:110px;')); ?>
		<?php 
                    $this->widget('CJuiDateTimePicker',array(
                    'model'=>$model, //Model object
                    'attribute'=>'endcharge_start', //attribute name
                    'mode'=>'datetime', //use "time","date" or "datetime" (default)
                    'options'=>array("dateFormat"=>'yy/mm/dd'), // jquery plugin options
                    'language' => ''
            )); ?>
	</div>
    
        <div class="row" style="width:25%;float:left;">
		<?php echo $form->label($model,'endcharge_end',array('style'=>'width:105px;')); ?>
		<?php 
                    $this->widget('CJuiDateTimePicker',array(
                    'model'=>$model, //Model object
                    'attribute'=>'endcharge_end', //attribute name
                    'mode'=>'datetime', //use "time","date" or "datetime" (default)
                    'options'=>array("dateFormat"=>'yy/mm/dd'), // jquery plugin options
                    'language' => ''
            )); ?>
	</div>
    
        <div class="row" style="float:left; width: 25%;">
		<?php echo $form->label($model,'sub_type',array('style'=>'width:105px;')); ?>
		<?php echo $form->dropDownList($model,'sub_type',array(''=>'Select',1=>'Pre-paid',2=>'Post-paid',3=>'Unknown')); ?>
	</div>
        <div class="row" style="width:25%;float:left">
        <?php echo $form->label($model, 'shortcode', array('style' => 'width:110px;')); ?>
        <?php echo $form->dropDownList($model, 'shortcode', Service::model()->getShortcode(), array('style' => 'width:140px;')); ?>
    	</div>
        <div class="row" style="float: left; width:25%">
		<?php echo $form->label($model,'option',array('style'=>'width:105px;')); ?>
		<?php echo $form->dropDownList($model,'option',array(''=>'Select',1=>'Full',2=>'Member Test',3=>'Only Customer')); ?>
	</div>
    	<div class="clear"></div>
	<div class="row buttons">
        <?php echo CHtml::submitButton('Search'); ?>&nbsp;&nbsp;&nbsp;&nbsp;
        <?php echo CHtml::button('Export', array('url' => Yii::app()->createUrl(''), 'id' => 'btn-export')); ?>
        <?php echo CHtml::link('Create Member', array('member/create'),array('class'=>'downfile','style'=>'margin-left:50px;'));?>
        <?php echo CHtml::link('Import Member', array('member/import'),array('class'=>'downfile','style'=>'margin-left:50px;'));?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

html/protected/views/member/_search1.php
<?php
/* @var $this MemberController */
/* @var $model Member */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php 
    Yii::import('application.extensions.CJuiDateTimePicker.CJuiDateTimePicker');
    $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
        'enableAjaxValidation' => FALSE,
	'method'=>'get',
)); ?>

	<div class="row" style="width:25%;float:left">
		<?php echo $form->label($model,'Phone Number',array('style'=>'width:110px;')); ?>
		<?php echo $form->textField($model,'msisdn',array('size'=>20,'maxlength'=>50)); ?>
	</div>
    
        <div class="row" style="width:25%;float:left">
		<?php echo $form->label($model,'category_id',array('style'=>'width:105px;')); ?>
		<?php echo $form->dropDownlist($model,'category_id',  Service::model()->getListCategory()); ?>
	</div>

	<div class="row" style="width:25%;float:left;">
		<?php echo $form->label($model,'service_id',array('style'=>'width:110px;')); ?>
		<?php echo $form->dropDownList($model,'service_id',$model->getListService(),array('style'=>'width:140px;')); ?>
	</div>
    
        <div class="row" style="width:25%;float:left;">
		<?php echo $form->label($model,'status',array('style'=>'width:105px;')); ?>
		<?php echo $form->dropDownList($model,'status',array('' => 'Select',1=>'Active',2=>'Suspend',3=>'Cancel',4=>'Cancel By System',5=>'Cancel by admin')); ?>
	</div>
    
        <div class="row" style="width:25%;float:left">
		<?php echo $form->label($model,'register_start',array('style'=>'width:110px;')); ?>
		<?php 
                    $this->widget('CJuiDateTimePicker',array(
                    'model'=>$model, //Model object
                    'attribute'=>'register_start', //attribute name
                    'mode'=>'datetime', //use "time","date" or "datetime" (default)
                    'options'=>array("dateFormat"=>'yy/mm/dd'), // jquery plugin options
                    'language' => ''
            )); ?>
	</div>
    
        <div class="row" style="width:25%;float:left;">
		<?php echo $form->label($model,'register_end',array('style'=>'width:105px;')); ?>
		<?php 
                    $this->widget('CJuiDateTimePicker',array(
                    'model'=>$model, //Model object
                    'attribute'=>'register_end', //attribute name
                    'mode'=>'datetime', //use "time","date" or "datetime" (default)
                    'options'=>array("dateFormat"=>'yy/mm/dd'), // jquery plugin options
                    'language' => ''
            )); ?>
	</div>
    
        <div class="row" style="width:25%;float:left">
		<?php echo $form->label($model,'cancel_start',array('style'=>'width:110px;')); ?>
		<?php 
                    $this->widget('CJuiDateTimePicker',array(
                    'model'=>$model, //Model object
                    'attribute'=>'cancel_start', //attribute name
                    'mode'=>'datetime', //use "time","date" or "datetime" (default)
                    'options'=>array("dateFormat"=>'yy/mm/dd'), // jquery plugin options
                    'language' => ''
            )); ?>
	</div>
    
        <div class="row" style="width:25%;float:left;">
		<?php echo $form->label($model,'cancel_end',array('style'=>'width:105px;')); ?>
		<?php 
                    $this->widget('CJuiDateTimePicker',array(
                    'model'=>$model, //Model object
                    'attribute'=>'cancel_end', //attribute name
                    'mode'=>'datetime', //use "time","date" or "datetime" (default)
                    'options'=>array("dateFormat"=>'yy/mm/dd'), // jquery plugin options
                    'language' => ''
            )); ?>
	</div>
    
        <div class="row" style="width:25%;float:left">
		<?php echo $form->label($model,'charging_start',array('style'=>'width:110px;')); ?>
		<?php 
                    $this->widget('CJuiDateTimePicker',array(
                    'model'=>$model, //Model object
                    'attribute'=>'charging_start', //attribute name
                    'mode'=>'datetime', //use "time","date" or "datetime" (default)
                    'options'=>array("dateFormat"=>'yy/mm/dd'), // jquery plugin options
                    'language' => ''
            )); ?>
	</div>
    
        <div class="row" style="width:25%;float:left;">
		<?php echo $form->label($model,'charging_end',array('style'=>'width:105px;')); ?>
		<?php 
                    $this->widget('CJuiDateTimePicker',array(
                    'model'=>$model, //Model object
                    'attribute'=>'charging_end', //attribute name
                    'mode'=>'datetime', //use "time","date" or "datetime" (default)
                    'options'=>array("dateFormat"=>'yy/mm/dd'), // jquery plugin options
                    'language' => ''
            )); ?>
	</div>
    
        <div class="row" style="width:25%;float:left">
		<?php echo $form->label($model,'endcharge_start',array('style'=>'width:110px;')); ?>
		<?php 
                    $this->widget('CJuiDateTimePicker',array(
                    'model'=>$model, //Model object
                    'attribute'=>'endcharge_start', //attribute name
                    'mode'=>'datetime', //use "time","date" or "datetime" (default)
                    'options'=>array("dateFormat"=>'yy/mm/dd'), // jquery plugin options
                    'language' => ''
            )); ?>
	</div>
    
        <div class="row" style="width:25%;float:left;">
		<?php echo $form->label($model,'endcharge_end',array('style'=>'width:105px;')); ?>
		<?php 
                    $this->widget('CJuiDateTimePicker',array(
                    'model'=>$model, //Model object
                    'attribute'=>'endcharge_end', //attribute name
                    'mode'=>'datetime', //use "time","date" or "datetime" (default)
                    'options'=>array("dateFormat"=>'yy/mm/dd'), // jquery plugin options
                    'language' => ''
            )); ?>
	</div>
    
        <div class="row" style="float:left; width: 25%;">
		<?php echo $form->label($model,'sub_type',array('style'=>'width:105px;')); ?>
		<?php echo $form->dropDownList($model,'sub_type',array(''=>'Select',1=>'Pre-paid',2=>'Post-paid',3=>'Unknown')); ?>
	</div>
        
        <div class="row" style="float: left; width:75%">
		<?php echo $form->label($model,'option',array('style'=>'width:105px;')); ?>
		<?php echo $form->dropDownList($model,'option',array(''=>'Select',1=>'Full',2=>'Member Test',3=>'Only Customer')); ?>
	</div>

	<div class="row buttons">
        <?php echo CHtml::submitButton('Search'); ?>&nbsp;&nbsp;&nbsp;&nbsp;
        <?php echo CHtml::button('Export', array('url' => Yii::app()->createUrl(''), 'id' => 'btn-export')); ?>
        <?php echo CHtml::link('Create Member', array('member/create'),array('class'=>'downfile','style'=>'margin-left:50px;'));?>
        <?php echo CHtml::link('Import Member', array('member/import'),array('class'=>'downfile','style'=>'margin-left:50px;'));?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

html/protected/views/member/_view.php
<?php
/* @var $this MemberController */
/* @var $data Member */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('msisdn')); ?>:</b>
	<?php echo CHtml::encode($data->msisdn); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('service_id')); ?>:</b>
	<?php echo CHtml::encode($data->service_id); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('register_date')); ?>:</b>
	<?php echo CHtml::encode($data->register_date); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('start_free_date')); ?>:</b>
	<?php echo CHtml::encode($data->start_free_date); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('end_free_date')); ?>:</b>
	<?php echo CHtml::encode($data->end_free_date); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('start_charging_date')); ?>:</b>
	<?php echo CHtml::encode($data->start_charging_date); ?>
	<br />

	<?php /*
	<b><?php echo CHtml::encode($data->getAttributeLabel('end_charging_date')); ?>:</b>
	<?php echo CHtml::encode($data->end_charging_date); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('status')); ?>:</b>
	<?php echo CHtml::encode($data->status); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('total_try_charging')); ?>:</b>
	<?php echo CHtml::encode($data->total_try_charging); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('total_money')); ?>:</b>
	<?php echo CHtml::encode($data->total_money); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('cancel_date')); ?>:</b>
	<?php echo CHtml::encode($data->cancel_date); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('convert_status')); ?>:</b>
	<?php echo CHtml::encode($data->convert_status); ?>
	<br />

	*/ ?>

</div>

html/protected/views/member/admin.php
<?php
/* @var $this MemberController */
/* @var $model Member */

$this->breadcrumbs = array(
    'Members' => array('admin'),
    'Manage',
);

$this->menu = array(
    array('label' => 'Create Member', 'url' => array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('member-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
$provider   = $model->search();
?>

<?php // echo CHtml::link('Advanced Search','#',array('class'=>'search-button')); ?>
<div class="search-form">
    <?php
    $this->renderPartial('_search', array(
        'model' => $model,
    ));
    ?>
</div><!-- search-form -->

<div class="exportcsv">
    <?php
    $totalmember = $provider->getTotalItemCount();
    echo '<span style="padding-left:20px;"><strong>Total member</strong>: '.$totalmember.'</span>';
    ?>
</div>

<?php
$this->widget('zii.widgets.grid.CGridView', array(
    'id' => 'member-grid',
    'dataProvider' => $provider,
    'ajaxUpdate'=>false,
    'columns' => array(
        'id',
        'msisdn',
        array('name' => 'service_id', 'value' => '$data->serviceName'),
        'shortcode',
        array('name' => 'register_date', 'value' => '$data->registerDate'),
        array('name' => 'cancel_date', 'value' => '$data->cancelDate'),
        array('name' => 'status', 'value' => '$data->getStatus()'),
        'total_money',
        array('name'=>'sub_type','value'=>'$data->getSubType()'),
        /*
          'start_charging_date',
          'end_charging_date',
          'status',
          'total_try_charging',
          'total_money',
          'cancel_date',
          'convert_status',
         */
        array(
            'class' => 'CButtonColumn',
            'template' => '{view}{update}'
        ),
    ),
));
?>

html/protected/views/member/create.php
<?php
/* @var $this MemberController */
/* @var $model Member */

$this->breadcrumbs=array(
	'Members'=>array('admin'),
	'Create',
);

$this->menu=array(
	array('label'=>'Manage Member', 'url'=>array('admin')),
);
?>

<h1>Create Member</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>